spring.application.name=onlinemovieticketbookingsys

spring.datasource.url=jdbc:mysql://localhost:3306/moviebooking
spring.datasource.username=root
spring.datasource.password=Rosh@ni2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=mysupersecretkeymysupersecretkey